// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.Entities.Data;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(BloomyShopDbContext))]
    [Migration("20260922000621_AddQuantityToCustomizedBouquetFlowe")]
    partial class AddQuantityToCustomizedBouquetFlowe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.DAL.Entities.AddOn", b =>
                {
                    b.Property<int>("AddOnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddOnID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AddOnID");

                    b.ToTable("AddOns");

                    b.HasData(
                        new
                        {
                            AddOnID = 1,
                            Name = "Teddy Bear",
                            Price = 200m
                        },
                        new
                        {
                            AddOnID = 2,
                            Name = "Chocolate Box",
                            Price = 150m
                        },
                        new
                        {
                            AddOnID = 3,
                            Name = "Greeting Card",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            FullName = "Bloomy Admin",
                            Password = "Admin@123"
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.Bouquet", b =>
                {
                    b.Property<int>("BouquetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BouquetID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreparationTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SizeID")
                        .HasColumnType("int");

                    b.HasKey("BouquetID");

                    b.HasIndex("SizeID");

                    b.ToTable("Bouquets");

                    b.HasData(
                        new
                        {
                            BouquetID = 1,
                            Description = "A beautiful bouquet of fresh red roses.",
                            Image = "romantic-roses.jpg",
                            IsActive = true,
                            Name = "Romantic Roses",
                            PreparationTime = "30 minutes",
                            Price = 300m,
                            SizeID = 2
                        },
                        new
                        {
                            BouquetID = 2,
                            Description = "A colorful bouquet of fresh seasonal flowers.",
                            Image = "spring-garden.jpg",
                            IsActive = true,
                            Name = "Spring Garden",
                            PreparationTime = "40 minutes",
                            Price = 400m,
                            SizeID = 3
                        },
                        new
                        {
                            BouquetID = 3,
                            Description = "A cheerful bouquet featuring bright sunflowers.",
                            Image = "sunny-bouquet.jpg",
                            IsActive = true,
                            Name = "Sunny Bouquet",
                            PreparationTime = "25 minutes",
                            Price = 250m,
                            SizeID = 1
                        },
                        new
                        {
                            BouquetID = 4,
                            Description = "An elegant bouquet of white lilies and flowers.",
                            Image = "elegant-white.jpg",
                            IsActive = true,
                            Name = "Elegant White",
                            PreparationTime = "35 minutes",
                            Price = 350m,
                            SizeID = 2
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.BouquetFlower", b =>
                {
                    b.Property<int>("BouquetID")
                        .HasColumnType("int");

                    b.Property<int>("FlowerID")
                        .HasColumnType("int");

                    b.HasKey("BouquetID", "FlowerID");

                    b.HasIndex("FlowerID");

                    b.ToTable("BouquetFlowers");

                    b.HasData(
                        new
                        {
                            BouquetID = 1,
                            FlowerID = 1
                        },
                        new
                        {
                            BouquetID = 2,
                            FlowerID = 2
                        },
                        new
                        {
                            BouquetID = 2,
                            FlowerID = 4
                        },
                        new
                        {
                            BouquetID = 3,
                            FlowerID = 4
                        },
                        new
                        {
                            BouquetID = 4,
                            FlowerID = 3
                        },
                        new
                        {
                            BouquetID = 4,
                            FlowerID = 1
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.BouquetSize", b =>
                {
                    b.Property<int>("SizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeID"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeID");

                    b.ToTable("BouquetSizes");

                    b.HasData(
                        new
                        {
                            SizeID = 1,
                            BasePrice = 100m,
                            Size = "Small"
                        },
                        new
                        {
                            SizeID = 2,
                            BasePrice = 200m,
                            Size = "Medium"
                        },
                        new
                        {
                            SizeID = 3,
                            BasePrice = 300m,
                            Size = "Large"
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("CartID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            CartID = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 1
                        },
                        new
                        {
                            CartID = 2,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 2
                        },
                        new
                        {
                            CartID = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 3
                        },
                        new
                        {
                            CartID = 4,
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 4
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"));

                    b.Property<int?>("BouquetID")
                        .HasColumnType("int");

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomizedBouquetID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartItemID");

                    b.HasIndex("BouquetID");

                    b.HasIndex("CartID");

                    b.HasIndex("CustomizedBouquetID");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            CartItemID = 1,
                            BouquetID = 1,
                            CartID = 1,
                            Quantity = 2,
                            UnitPrice = 300m
                        },
                        new
                        {
                            CartItemID = 2,
                            BouquetID = 3,
                            CartID = 2,
                            Quantity = 1,
                            UnitPrice = 250m
                        },
                        new
                        {
                            CartItemID = 3,
                            CartID = 3,
                            CustomizedBouquetID = 3,
                            Quantity = 1,
                            UnitPrice = 0m
                        },
                        new
                        {
                            CartItemID = 4,
                            CartID = 4,
                            CustomizedBouquetID = 4,
                            Quantity = 1,
                            UnitPrice = 0m
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            City = "Damietta",
                            Email = "noor@example.com",
                            FName = "Noor",
                            FullName = "Noor Hassan",
                            Lname = "Hassan",
                            Password = "Customer@123",
                            Phone = "01000000001",
                            street = "Main Street"
                        },
                        new
                        {
                            CustomerID = 2,
                            City = "Cairo",
                            Email = "sara@example.com",
                            FName = "Sara",
                            FullName = "Sara Ahmed",
                            Lname = "Ahmed",
                            Password = "Customer@123",
                            Phone = "01000000002",
                            street = "Nile Street"
                        },
                        new
                        {
                            CustomerID = 3,
                            City = "Alexandria",
                            Email = "mariam@example.com",
                            FName = "Mariam",
                            FullName = "Mariam Ali",
                            Lname = "Ali",
                            Password = "Customer@123",
                            Phone = "01000000003",
                            street = "Corniche Street"
                        },
                        new
                        {
                            CustomerID = 4,
                            City = "Mansoura",
                            Email = "omar@example.com",
                            FName = "Omar",
                            FullName = "Omar Mohamed",
                            Lname = "Mohamed",
                            Password = "Customer@123",
                            Phone = "01000000004",
                            street = "University Street"
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomerBouquet", b =>
                {
                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("BouquetID")
                        .HasColumnType("int");

                    b.HasKey("CustomerID", "BouquetID");

                    b.HasIndex("BouquetID");

                    b.ToTable("CustomerBouquets");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            BouquetID = 1
                        },
                        new
                        {
                            CustomerID = 1,
                            BouquetID = 3
                        },
                        new
                        {
                            CustomerID = 2,
                            BouquetID = 2
                        },
                        new
                        {
                            CustomerID = 3,
                            BouquetID = 4
                        },
                        new
                        {
                            CustomerID = 4,
                            BouquetID = 1
                        },
                        new
                        {
                            CustomerID = 4,
                            BouquetID = 2
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquet", b =>
                {
                    b.Property<int>("CustomizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomizationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int>("SizeID")
                        .HasColumnType("int");

                    b.Property<int>("WrappingID")
                        .HasColumnType("int");

                    b.HasKey("CustomizationID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("SizeID");

                    b.HasIndex("WrappingID");

                    b.ToTable("CustomizedBouquets");

                    b.HasData(
                        new
                        {
                            CustomizationID = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 1,
                            PreparationTime = 45,
                            SizeID = 2,
                            WrappingID = 1
                        },
                        new
                        {
                            CustomizationID = 2,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 2,
                            PreparationTime = 60,
                            SizeID = 3,
                            WrappingID = 2
                        },
                        new
                        {
                            CustomizationID = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 3,
                            PreparationTime = 30,
                            SizeID = 1,
                            WrappingID = 3
                        },
                        new
                        {
                            CustomizationID = 4,
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 4,
                            PreparationTime = 50,
                            SizeID = 2,
                            WrappingID = 1
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetAddOn", b =>
                {
                    b.Property<int>("CustomizationID")
                        .HasColumnType("int");

                    b.Property<int>("AddOnID")
                        .HasColumnType("int");

                    b.HasKey("CustomizationID", "AddOnID");

                    b.HasIndex("AddOnID");

                    b.ToTable("CustomizedBouquetAddOns");

                    b.HasData(
                        new
                        {
                            CustomizationID = 1,
                            AddOnID = 1
                        },
                        new
                        {
                            CustomizationID = 1,
                            AddOnID = 3
                        },
                        new
                        {
                            CustomizationID = 2,
                            AddOnID = 2
                        },
                        new
                        {
                            CustomizationID = 3,
                            AddOnID = 3
                        },
                        new
                        {
                            CustomizationID = 4,
                            AddOnID = 1
                        },
                        new
                        {
                            CustomizationID = 4,
                            AddOnID = 2
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetFlower", b =>
                {
                    b.Property<int>("CustomizationID")
                        .HasColumnType("int");

                    b.Property<int>("FlowerID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CustomizationID", "FlowerID");

                    b.HasIndex("FlowerID");

                    b.ToTable("CustomizedBouquetFlowers");

                    b.HasData(
                        new
                        {
                            CustomizationID = 1,
                            FlowerID = 1,
                            Quantity = 0
                        },
                        new
                        {
                            CustomizationID = 1,
                            FlowerID = 3,
                            Quantity = 0
                        },
                        new
                        {
                            CustomizationID = 2,
                            FlowerID = 2,
                            Quantity = 0
                        },
                        new
                        {
                            CustomizationID = 2,
                            FlowerID = 4,
                            Quantity = 0
                        },
                        new
                        {
                            CustomizationID = 3,
                            FlowerID = 1,
                            Quantity = 0
                        },
                        new
                        {
                            CustomizationID = 4,
                            FlowerID = 3,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetFlowerColor", b =>
                {
                    b.Property<int>("CustomizationID")
                        .HasColumnType("int");

                    b.Property<int>("FlowerColorID")
                        .HasColumnType("int");

                    b.HasKey("CustomizationID", "FlowerColorID");

                    b.HasIndex("FlowerColorID");

                    b.ToTable("CustomizedBouquetFlowerColors");

                    b.HasData(
                        new
                        {
                            CustomizationID = 1,
                            FlowerColorID = 1
                        },
                        new
                        {
                            CustomizationID = 1,
                            FlowerColorID = 6
                        },
                        new
                        {
                            CustomizationID = 2,
                            FlowerColorID = 5
                        },
                        new
                        {
                            CustomizationID = 2,
                            FlowerColorID = 7
                        },
                        new
                        {
                            CustomizationID = 3,
                            FlowerColorID = 3
                        },
                        new
                        {
                            CustomizationID = 4,
                            FlowerColorID = 2
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.DecorationType", b =>
                {
                    b.Property<int>("DecorationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DecorationTypeID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DecorationTypeID");

                    b.ToTable("DecorationTypes");

                    b.HasData(
                        new
                        {
                            DecorationTypeID = 1,
                            Description = "Balloon decorations for events",
                            Name = "Balloon Decoration"
                        },
                        new
                        {
                            DecorationTypeID = 2,
                            Description = "Decorations for tables and dining areas",
                            Name = "Table Decoration"
                        },
                        new
                        {
                            DecorationTypeID = 3,
                            Description = "Flower arrangements for events",
                            Name = "Flower Decoration"
                        },
                        new
                        {
                            DecorationTypeID = 4,
                            Description = "Special decorations for weddings",
                            Name = "Wedding Decoration"
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.EventRequest", b =>
                {
                    b.Property<int>("EventRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventRequestID"));

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("AdminResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("OccasionID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventRequestID");

                    b.HasIndex("AdminID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("OccasionID");

                    b.ToTable("EventRequests");

                    b.HasData(
                        new
                        {
                            EventRequestID = 1,
                            AdminID = 1,
                            AdminResponse = "Request received and under review.",
                            Budget = 5000m,
                            CustomerID = 1,
                            EventDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "Indoor",
                            NumberOfGuests = 50,
                            OccasionID = 1,
                            Status = "Pending",
                            Theme = "Romantic"
                        },
                        new
                        {
                            EventRequestID = 2,
                            AdminID = 1,
                            AdminResponse = "Request approved.",
                            Budget = 10000m,
                            CustomerID = 2,
                            EventDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "Outdoor",
                            NumberOfGuests = 100,
                            OccasionID = 2,
                            Status = "Approved",
                            Theme = "Elegant Garden"
                        },
                        new
                        {
                            EventRequestID = 3,
                            Budget = 3000m,
                            CustomerID = 3,
                            EventDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationType = "Indoor",
                            NumberOfGuests = 30,
                            OccasionID = 3,
                            Status = "Pending",
                            Theme = "Simple and Elegant"
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.EventRequestDecoration", b =>
                {
                    b.Property<int>("EventRequestID")
                        .HasColumnType("int");

                    b.Property<int>("DecorationTypeID")
                        .HasColumnType("int");

                    b.HasKey("EventRequestID", "DecorationTypeID");

                    b.HasIndex("DecorationTypeID");

                    b.ToTable("EventRequestDecorations");

                    b.HasData(
                        new
                        {
                            EventRequestID = 1,
                            DecorationTypeID = 1
                        },
                        new
                        {
                            EventRequestID = 1,
                            DecorationTypeID = 2
                        },
                        new
                        {
                            EventRequestID = 2,
                            DecorationTypeID = 3
                        },
                        new
                        {
                            EventRequestID = 2,
                            DecorationTypeID = 4
                        },
                        new
                        {
                            EventRequestID = 3,
                            DecorationTypeID = 1
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.Flower", b =>
                {
                    b.Property<int>("FlowerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlowerID"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FlowerID");

                    b.ToTable("Flowers");

                    b.HasData(
                        new
                        {
                            FlowerID = 1,
                            BasePrice = 50m,
                            Image = "rose.jpg",
                            Name = "Rose",
                            Quantity = 100
                        },
                        new
                        {
                            FlowerID = 2,
                            BasePrice = 40m,
                            Image = "tulip.jpg",
                            Name = "Tulip",
                            Quantity = 80
                        },
                        new
                        {
                            FlowerID = 3,
                            BasePrice = 45m,
                            Image = "lily.jpg",
                            Name = "Lily",
                            Quantity = 70
                        },
                        new
                        {
                            FlowerID = 4,
                            BasePrice = 35m,
                            Image = "sunflower.jpg",
                            Name = "Sunflower",
                            Quantity = 60
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.FlowerColor", b =>
                {
                    b.Property<int>("FlowerColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlowerColorID"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlowerID")
                        .HasColumnType("int");

                    b.HasKey("FlowerColorID");

                    b.HasIndex("FlowerID");

                    b.ToTable("FlowerColors");

                    b.HasData(
                        new
                        {
                            FlowerColorID = 1,
                            Color = "Red",
                            FlowerID = 1
                        },
                        new
                        {
                            FlowerColorID = 2,
                            Color = "White",
                            FlowerID = 1
                        },
                        new
                        {
                            FlowerColorID = 3,
                            Color = "Pink",
                            FlowerID = 1
                        },
                        new
                        {
                            FlowerColorID = 4,
                            Color = "Yellow",
                            FlowerID = 2
                        },
                        new
                        {
                            FlowerColorID = 5,
                            Color = "Pink",
                            FlowerID = 2
                        },
                        new
                        {
                            FlowerColorID = 6,
                            Color = "White",
                            FlowerID = 3
                        },
                        new
                        {
                            FlowerColorID = 7,
                            Color = "Orange",
                            FlowerID = 4
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.Occasion", b =>
                {
                    b.Property<int>("OccasionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OccasionID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OccasionID");

                    b.ToTable("Occasions");

                    b.HasData(
                        new
                        {
                            OccasionID = 1,
                            Name = "Wedding"
                        },
                        new
                        {
                            OccasionID = 2,
                            Name = "Birthday"
                        },
                        new
                        {
                            OccasionID = 3,
                            Name = "Engagement"
                        },
                        new
                        {
                            OccasionID = 4,
                            Name = "Graduation"
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            CustomerID = 1,
                            DeliveryAddress = "Main Street, Damietta",
                            OrderDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalPrice = 600m
                        },
                        new
                        {
                            OrderID = 2,
                            CustomerID = 2,
                            DeliveryAddress = "Nile Street, Cairo",
                            OrderDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed",
                            TotalPrice = 250m
                        },
                        new
                        {
                            OrderID = 3,
                            CustomerID = 3,
                            DeliveryAddress = "Corniche Street, Alexandria",
                            OrderDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            TotalPrice = 350m
                        },
                        new
                        {
                            OrderID = 4,
                            CustomerID = 4,
                            DeliveryAddress = "University Street, Mansoura",
                            OrderDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalPrice = 400m
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<int?>("BouquetID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomizedBouquetID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemID");

                    b.HasIndex("BouquetID");

                    b.HasIndex("CustomizedBouquetID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemID = 1,
                            BouquetID = 1,
                            OrderID = 1,
                            Quantity = 2,
                            UnitPrice = 300m
                        },
                        new
                        {
                            OrderItemID = 2,
                            BouquetID = 3,
                            OrderID = 2,
                            Quantity = 1,
                            UnitPrice = 250m
                        },
                        new
                        {
                            OrderItemID = 3,
                            CustomizedBouquetID = 3,
                            OrderID = 3,
                            Quantity = 1,
                            UnitPrice = 350m
                        },
                        new
                        {
                            OrderItemID = 4,
                            BouquetID = 2,
                            OrderID = 4,
                            Quantity = 1,
                            UnitPrice = 400m
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.Wrapping", b =>
                {
                    b.Property<int>("WrappingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WrappingID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WrappingID");

                    b.ToTable("Wrappings");

                    b.HasData(
                        new
                        {
                            WrappingID = 1,
                            Name = "Classic",
                            Price = 50m
                        },
                        new
                        {
                            WrappingID = 2,
                            Name = "Luxury",
                            Price = 100m
                        },
                        new
                        {
                            WrappingID = 3,
                            Name = "Premium",
                            Price = 150m
                        });
                });

            modelBuilder.Entity("Project.DAL.Entities.Bouquet", b =>
                {
                    b.HasOne("Project.DAL.Entities.BouquetSize", "BouquetSize")
                        .WithMany("Bouquets")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BouquetSize");
                });

            modelBuilder.Entity("Project.DAL.Entities.BouquetFlower", b =>
                {
                    b.HasOne("Project.DAL.Entities.Bouquet", "Bouquet")
                        .WithMany("BouquetFlowers")
                        .HasForeignKey("BouquetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.Flower", "Flower")
                        .WithMany("BouquetFlowers")
                        .HasForeignKey("FlowerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("Flower");
                });

            modelBuilder.Entity("Project.DAL.Entities.Cart", b =>
                {
                    b.HasOne("Project.DAL.Entities.Customer", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("Project.DAL.Entities.Cart", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Project.DAL.Entities.CartItem", b =>
                {
                    b.HasOne("Project.DAL.Entities.Bouquet", "Bouquet")
                        .WithMany("CartItems")
                        .HasForeignKey("BouquetID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.DAL.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.CustomizedBouquet", "CustomizedBouquet")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomizedBouquetID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bouquet");

                    b.Navigation("Cart");

                    b.Navigation("CustomizedBouquet");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomerBouquet", b =>
                {
                    b.HasOne("Project.DAL.Entities.Bouquet", "Bouquet")
                        .WithMany("CustomerBouquets")
                        .HasForeignKey("BouquetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.Customer", "Customer")
                        .WithMany("CustomerBouquets")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquet", b =>
                {
                    b.HasOne("Project.DAL.Entities.Customer", "Customer")
                        .WithMany("CustomizedBouquets")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.BouquetSize", "BouquetSize")
                        .WithMany("CustomizedBouquets")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.Wrapping", "Wrapping")
                        .WithMany("CustomizedBouquets")
                        .HasForeignKey("WrappingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BouquetSize");

                    b.Navigation("Customer");

                    b.Navigation("Wrapping");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetAddOn", b =>
                {
                    b.HasOne("Project.DAL.Entities.AddOn", "AddOn")
                        .WithMany("CustomizedBouquetAddOns")
                        .HasForeignKey("AddOnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.CustomizedBouquet", "CustomizedBouquet")
                        .WithMany("CustomizedBouquetAddOns")
                        .HasForeignKey("CustomizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("CustomizedBouquet");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetFlower", b =>
                {
                    b.HasOne("Project.DAL.Entities.CustomizedBouquet", "CustomizedBouquet")
                        .WithMany("CustomizedBouquetFlowers")
                        .HasForeignKey("CustomizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.Flower", "Flower")
                        .WithMany("CustomizedBouquetFlowers")
                        .HasForeignKey("FlowerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomizedBouquet");

                    b.Navigation("Flower");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetFlowerColor", b =>
                {
                    b.HasOne("Project.DAL.Entities.CustomizedBouquet", "CustomizedBouquet")
                        .WithMany("CustomizedBouquetFlowerColors")
                        .HasForeignKey("CustomizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.FlowerColor", "FlowerColor")
                        .WithMany("CustomizedBouquetFlowerColors")
                        .HasForeignKey("FlowerColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomizedBouquet");

                    b.Navigation("FlowerColor");
                });

            modelBuilder.Entity("Project.DAL.Entities.EventRequest", b =>
                {
                    b.HasOne("Project.DAL.Entities.Admin", "Admin")
                        .WithMany("ReviewedEventRequests")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Project.DAL.Entities.Customer", "Customer")
                        .WithMany("EventRequests")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.Occasion", "Occasion")
                        .WithMany("EventRequests")
                        .HasForeignKey("OccasionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("Project.DAL.Entities.EventRequestDecoration", b =>
                {
                    b.HasOne("Project.DAL.Entities.DecorationType", "DecorationType")
                        .WithMany("EventRequestDecorations")
                        .HasForeignKey("DecorationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.EventRequest", "EventRequest")
                        .WithMany("EventRequestDecorations")
                        .HasForeignKey("EventRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecorationType");

                    b.Navigation("EventRequest");
                });

            modelBuilder.Entity("Project.DAL.Entities.FlowerColor", b =>
                {
                    b.HasOne("Project.DAL.Entities.Flower", "Flower")
                        .WithMany("FlowerColors")
                        .HasForeignKey("FlowerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flower");
                });

            modelBuilder.Entity("Project.DAL.Entities.Order", b =>
                {
                    b.HasOne("Project.DAL.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Project.DAL.Entities.OrderItem", b =>
                {
                    b.HasOne("Project.DAL.Entities.Bouquet", "Bouquet")
                        .WithMany("OrderItems")
                        .HasForeignKey("BouquetID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.DAL.Entities.CustomizedBouquet", "CustomizedBouquet")
                        .WithMany("OrderItems")
                        .HasForeignKey("CustomizedBouquetID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.DAL.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("CustomizedBouquet");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Project.DAL.Entities.AddOn", b =>
                {
                    b.Navigation("CustomizedBouquetAddOns");
                });

            modelBuilder.Entity("Project.DAL.Entities.Admin", b =>
                {
                    b.Navigation("ReviewedEventRequests");
                });

            modelBuilder.Entity("Project.DAL.Entities.Bouquet", b =>
                {
                    b.Navigation("BouquetFlowers");

                    b.Navigation("CartItems");

                    b.Navigation("CustomerBouquets");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Project.DAL.Entities.BouquetSize", b =>
                {
                    b.Navigation("Bouquets");

                    b.Navigation("CustomizedBouquets");
                });

            modelBuilder.Entity("Project.DAL.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Project.DAL.Entities.Customer", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("CustomerBouquets");

                    b.Navigation("CustomizedBouquets");

                    b.Navigation("EventRequests");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquet", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("CustomizedBouquetAddOns");

                    b.Navigation("CustomizedBouquetFlowerColors");

                    b.Navigation("CustomizedBouquetFlowers");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Project.DAL.Entities.DecorationType", b =>
                {
                    b.Navigation("EventRequestDecorations");
                });

            modelBuilder.Entity("Project.DAL.Entities.EventRequest", b =>
                {
                    b.Navigation("EventRequestDecorations");
                });

            modelBuilder.Entity("Project.DAL.Entities.Flower", b =>
                {
                    b.Navigation("BouquetFlowers");

                    b.Navigation("CustomizedBouquetFlowers");

                    b.Navigation("FlowerColors");
                });

            modelBuilder.Entity("Project.DAL.Entities.FlowerColor", b =>
                {
                    b.Navigation("CustomizedBouquetFlowerColors");
                });

            modelBuilder.Entity("Project.DAL.Entities.Occasion", b =>
                {
                    b.Navigation("EventRequests");
                });

            modelBuilder.Entity("Project.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Project.DAL.Entities.Wrapping", b =>
                {
                    b.Navigation("CustomizedBouquets");
                });
#pragma warning restore 612, 618
        }
    }
}
