// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.Entities.Data;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(BloomyShopDbContext))]
    partial class BloomyShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.DAL.Entities.AddOn", b =>
                {
                    b.Property<int>("AddOnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddOnID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AddOnID");

                    b.ToTable("AddOns");
                });

            modelBuilder.Entity("Project.DAL.Entities.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Project.DAL.Entities.Bouquet", b =>
                {
                    b.Property<int>("BouquetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BouquetID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreparationTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SizeID")
                        .HasColumnType("int");

                    b.HasKey("BouquetID");

                    b.HasIndex("SizeID");

                    b.ToTable("Bouquets");
                });

            modelBuilder.Entity("Project.DAL.Entities.BouquetFlower", b =>
                {
                    b.Property<int>("BouquetID")
                        .HasColumnType("int");

                    b.Property<int>("FlowerID")
                        .HasColumnType("int");

                    b.HasKey("BouquetID", "FlowerID");

                    b.HasIndex("FlowerID");

                    b.ToTable("BouquetFlowers");
                });

            modelBuilder.Entity("Project.DAL.Entities.BouquetSize", b =>
                {
                    b.Property<int>("SizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeID"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeID");

                    b.ToTable("BouquetSizes");
                });

            modelBuilder.Entity("Project.DAL.Entities.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("CartID");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Project.DAL.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"));

                    b.Property<int?>("BouquetID")
                        .HasColumnType("int");

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomizedBouquetID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartItemID");

                    b.HasIndex("BouquetID");

                    b.HasIndex("CartID");

                    b.HasIndex("CustomizedBouquetID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Project.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomerBouquet", b =>
                {
                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("BouquetID")
                        .HasColumnType("int");

                    b.HasKey("CustomerID", "BouquetID");

                    b.HasIndex("BouquetID");

                    b.ToTable("CustomerBouquets");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquet", b =>
                {
                    b.Property<int>("CustomizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomizationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int>("SizeID")
                        .HasColumnType("int");

                    b.Property<int>("WrappingID")
                        .HasColumnType("int");

                    b.HasKey("CustomizationID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("SizeID");

                    b.HasIndex("WrappingID");

                    b.ToTable("CustomizedBouquets");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetAddOn", b =>
                {
                    b.Property<int>("CustomizationID")
                        .HasColumnType("int");

                    b.Property<int>("AddOnID")
                        .HasColumnType("int");

                    b.HasKey("CustomizationID", "AddOnID");

                    b.HasIndex("AddOnID");

                    b.ToTable("CustomizedBouquetAddOns");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetFlower", b =>
                {
                    b.Property<int>("CustomizationID")
                        .HasColumnType("int");

                    b.Property<int>("FlowerID")
                        .HasColumnType("int");

                    b.HasKey("CustomizationID", "FlowerID");

                    b.HasIndex("FlowerID");

                    b.ToTable("CustomizedBouquetFlowers");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetFlowerColor", b =>
                {
                    b.Property<int>("CustomizationID")
                        .HasColumnType("int");

                    b.Property<int>("FlowerColorID")
                        .HasColumnType("int");

                    b.HasKey("CustomizationID", "FlowerColorID");

                    b.HasIndex("FlowerColorID");

                    b.ToTable("CustomizedBouquetFlowerColors");
                });

            modelBuilder.Entity("Project.DAL.Entities.DecorationType", b =>
                {
                    b.Property<int>("DecorationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DecorationTypeID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DecorationTypeID");

                    b.ToTable("DecorationTypes");
                });

            modelBuilder.Entity("Project.DAL.Entities.EventRequest", b =>
                {
                    b.Property<int>("EventRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventRequestID"));

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("AdminResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("OccasionID")
                        .HasColumnType("int");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventRequestID");

                    b.HasIndex("AdminID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("OccasionID");

                    b.ToTable("EventRequests");
                });

            modelBuilder.Entity("Project.DAL.Entities.EventRequestDecoration", b =>
                {
                    b.Property<int>("EventRequestID")
                        .HasColumnType("int");

                    b.Property<int>("DecorationTypeID")
                        .HasColumnType("int");

                    b.HasKey("EventRequestID", "DecorationTypeID");

                    b.HasIndex("DecorationTypeID");

                    b.ToTable("EventRequestDecorations");
                });

            modelBuilder.Entity("Project.DAL.Entities.Flower", b =>
                {
                    b.Property<int>("FlowerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlowerID"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FlowerID");

                    b.ToTable("Flowers");
                });

            modelBuilder.Entity("Project.DAL.Entities.FlowerColor", b =>
                {
                    b.Property<int>("FlowerColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlowerColorID"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlowerID")
                        .HasColumnType("int");

                    b.HasKey("FlowerColorID");

                    b.HasIndex("FlowerID");

                    b.ToTable("FlowerColors");
                });

            modelBuilder.Entity("Project.DAL.Entities.Occasion", b =>
                {
                    b.Property<int>("OccasionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OccasionID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OccasionID");

                    b.ToTable("Occasions");
                });

            modelBuilder.Entity("Project.DAL.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.DAL.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<int?>("BouquetID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomizedBouquetID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemID");

                    b.HasIndex("BouquetID");

                    b.HasIndex("CustomizedBouquetID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Project.DAL.Entities.Wrapping", b =>
                {
                    b.Property<int>("WrappingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WrappingID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WrappingID");

                    b.ToTable("Wrappings");
                });

            modelBuilder.Entity("Project.DAL.Entities.Bouquet", b =>
                {
                    b.HasOne("Project.DAL.Entities.BouquetSize", "BouquetSize")
                        .WithMany("Bouquets")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BouquetSize");
                });

            modelBuilder.Entity("Project.DAL.Entities.BouquetFlower", b =>
                {
                    b.HasOne("Project.DAL.Entities.Bouquet", "Bouquet")
                        .WithMany("BouquetFlowers")
                        .HasForeignKey("BouquetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.Flower", "Flower")
                        .WithMany("BouquetFlowers")
                        .HasForeignKey("FlowerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("Flower");
                });

            modelBuilder.Entity("Project.DAL.Entities.Cart", b =>
                {
                    b.HasOne("Project.DAL.Entities.Customer", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("Project.DAL.Entities.Cart", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Project.DAL.Entities.CartItem", b =>
                {
                    b.HasOne("Project.DAL.Entities.Bouquet", "Bouquet")
                        .WithMany("CartItems")
                        .HasForeignKey("BouquetID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.DAL.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.CustomizedBouquet", "CustomizedBouquet")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomizedBouquetID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bouquet");

                    b.Navigation("Cart");

                    b.Navigation("CustomizedBouquet");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomerBouquet", b =>
                {
                    b.HasOne("Project.DAL.Entities.Bouquet", "Bouquet")
                        .WithMany("CustomerBouquets")
                        .HasForeignKey("BouquetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.Customer", "Customer")
                        .WithMany("CustomerBouquets")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquet", b =>
                {
                    b.HasOne("Project.DAL.Entities.Customer", "Customer")
                        .WithMany("CustomizedBouquets")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.BouquetSize", "BouquetSize")
                        .WithMany("CustomizedBouquets")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.Wrapping", "Wrapping")
                        .WithMany("CustomizedBouquets")
                        .HasForeignKey("WrappingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BouquetSize");

                    b.Navigation("Customer");

                    b.Navigation("Wrapping");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetAddOn", b =>
                {
                    b.HasOne("Project.DAL.Entities.AddOn", "AddOn")
                        .WithMany("CustomizedBouquetAddOns")
                        .HasForeignKey("AddOnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.CustomizedBouquet", "CustomizedBouquet")
                        .WithMany("CustomizedBouquetAddOns")
                        .HasForeignKey("CustomizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("CustomizedBouquet");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetFlower", b =>
                {
                    b.HasOne("Project.DAL.Entities.CustomizedBouquet", "CustomizedBouquet")
                        .WithMany("CustomizedBouquetFlowers")
                        .HasForeignKey("CustomizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.Flower", "Flower")
                        .WithMany("CustomizedBouquetFlowers")
                        .HasForeignKey("FlowerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomizedBouquet");

                    b.Navigation("Flower");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquetFlowerColor", b =>
                {
                    b.HasOne("Project.DAL.Entities.CustomizedBouquet", "CustomizedBouquet")
                        .WithMany("CustomizedBouquetFlowerColors")
                        .HasForeignKey("CustomizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.FlowerColor", "FlowerColor")
                        .WithMany("CustomizedBouquetFlowerColors")
                        .HasForeignKey("FlowerColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomizedBouquet");

                    b.Navigation("FlowerColor");
                });

            modelBuilder.Entity("Project.DAL.Entities.EventRequest", b =>
                {
                    b.HasOne("Project.DAL.Entities.Admin", "Admin")
                        .WithMany("ReviewedEventRequests")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Project.DAL.Entities.Customer", "Customer")
                        .WithMany("EventRequests")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.Occasion", "Occasion")
                        .WithMany("EventRequests")
                        .HasForeignKey("OccasionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("Project.DAL.Entities.EventRequestDecoration", b =>
                {
                    b.HasOne("Project.DAL.Entities.DecorationType", "DecorationType")
                        .WithMany("EventRequestDecorations")
                        .HasForeignKey("DecorationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.DAL.Entities.EventRequest", "EventRequest")
                        .WithMany("EventRequestDecorations")
                        .HasForeignKey("EventRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecorationType");

                    b.Navigation("EventRequest");
                });

            modelBuilder.Entity("Project.DAL.Entities.FlowerColor", b =>
                {
                    b.HasOne("Project.DAL.Entities.Flower", "Flower")
                        .WithMany("FlowerColors")
                        .HasForeignKey("FlowerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flower");
                });

            modelBuilder.Entity("Project.DAL.Entities.Order", b =>
                {
                    b.HasOne("Project.DAL.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Project.DAL.Entities.OrderItem", b =>
                {
                    b.HasOne("Project.DAL.Entities.Bouquet", "Bouquet")
                        .WithMany("OrderItems")
                        .HasForeignKey("BouquetID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.DAL.Entities.CustomizedBouquet", "CustomizedBouquet")
                        .WithMany("OrderItems")
                        .HasForeignKey("CustomizedBouquetID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.DAL.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("CustomizedBouquet");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Project.DAL.Entities.AddOn", b =>
                {
                    b.Navigation("CustomizedBouquetAddOns");
                });

            modelBuilder.Entity("Project.DAL.Entities.Admin", b =>
                {
                    b.Navigation("ReviewedEventRequests");
                });

            modelBuilder.Entity("Project.DAL.Entities.Bouquet", b =>
                {
                    b.Navigation("BouquetFlowers");

                    b.Navigation("CartItems");

                    b.Navigation("CustomerBouquets");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Project.DAL.Entities.BouquetSize", b =>
                {
                    b.Navigation("Bouquets");

                    b.Navigation("CustomizedBouquets");
                });

            modelBuilder.Entity("Project.DAL.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Project.DAL.Entities.Customer", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("CustomerBouquets");

                    b.Navigation("CustomizedBouquets");

                    b.Navigation("EventRequests");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Project.DAL.Entities.CustomizedBouquet", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("CustomizedBouquetAddOns");

                    b.Navigation("CustomizedBouquetFlowerColors");

                    b.Navigation("CustomizedBouquetFlowers");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Project.DAL.Entities.DecorationType", b =>
                {
                    b.Navigation("EventRequestDecorations");
                });

            modelBuilder.Entity("Project.DAL.Entities.EventRequest", b =>
                {
                    b.Navigation("EventRequestDecorations");
                });

            modelBuilder.Entity("Project.DAL.Entities.Flower", b =>
                {
                    b.Navigation("BouquetFlowers");

                    b.Navigation("CustomizedBouquetFlowers");

                    b.Navigation("FlowerColors");
                });

            modelBuilder.Entity("Project.DAL.Entities.FlowerColor", b =>
                {
                    b.Navigation("CustomizedBouquetFlowerColors");
                });

            modelBuilder.Entity("Project.DAL.Entities.Occasion", b =>
                {
                    b.Navigation("EventRequests");
                });

            modelBuilder.Entity("Project.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Project.DAL.Entities.Wrapping", b =>
                {
                    b.Navigation("CustomizedBouquets");
                });
#pragma warning restore 612, 618
        }
    }
}
